#!/usr/bin/env python3
"""Trace the dog*.png frames into 1-bit pixel-art sprites for the pet UI.

All frames share ONE fixed scale (anchored to the sitting frame) and are
bottom-aligned (feet on a common floor) + horizontally centred, so squash /
stretch poses keep their real height differences (crouch shorter, jump taller)
and every frame lands on the same ground line.  Run from this directory;
with --emit it (re)writes petsprite.h.
"""
import os, sys
import numpy as np
from PIL import Image, ImageDraw, ImageFont

DIR = os.path.dirname(os.path.abspath(__file__))
OUT = DIR + "/petsprite.h"
BAND = (226, 599)        # puppy band, excludes the "PET" label below
PH = 52                  # sitting-dog height in sprite px (sets the fixed scale)
PAD_X, PAD_Y = 2, 2      # canvas margins
TH_INK = 180

FRAMES = [               # (C name, source png)
    ("pet_idle",      "dog.png"),
    ("pet_blink",     "dog_blink.png"),
    ("pet_happy",     "dog_happy.png"),
    ("pet_sad",       "dog_sad.png"),
    ("pet_eat",       "dog_eat.png"),
    ("pet_eat_closed","dog_eat_closed.png"),
    ("pet_look",      "dog_look.png"),
    ("pet_look_half", "dog_look_half.png"),
    ("pet_crouch",    "dog_crouch.png"),
    ("pet_jump",      "dog_jump.png"),
    ("pet_walk1",     "dog_walk1.png"),
    ("pet_walk2",     "dog_walk2.png"),
    ("pet_walk3",     "dog_walk3.png"),
    ("pet_walk4",     "dog_walk4.png"),
]

def gray(name):
    return np.asarray(Image.open(f"{DIR}/{name}").convert("L")).astype(int)

def bbox(name):
    a = gray(name)[BAND[0]:BAND[1], :] < 150
    xs = np.where(a.any(0))[0]; ys = np.where(a.any(1))[0]
    return xs[0], BAND[0]+ys[0], xs[-1], BAND[0]+ys[-1]

BOXES = {src: bbox(src) for _, src in FRAMES}
# fixed scale from the sitting frame's height
sx0, sy0, sx1, sy1 = BOXES["dog.png"]
SCALE = PH / (sy1 - sy0 + 1)

def scaled(src):
    x0, y0, x1, y1 = BOXES[src]
    return src, x0, y0, x1, y1, int(round((x1-x0+1)*SCALE)), int(round((y1-y0+1)*SCALE))

DIMS = [scaled(src) for _, src in FRAMES]
PET_W = max(d[5] for d in DIMS) + 2*PAD_X
PET_H = max(d[6] for d in DIMS) + 2*PAD_Y
print(f"scale={SCALE:.4f}  canvas={PET_W}x{PET_H}")

def trace(src):
    _, x0, y0, x1, y1, tw, th = scaled(src)
    a = gray(src)[y0:y1+1, x0:x1+1]
    ox = (PET_W - tw)//2          # centre horizontally
    oy = PET_H - PAD_Y - th       # bottom-align (feet on the floor)
    g = [[0]*PET_W for _ in range(PET_H)]
    for ty in range(th):
        for tx in range(tw):
            yy0=int(ty/SCALE); yy1=max(yy0+1,int((ty+1)/SCALE))
            xx0=int(tx/SCALE); xx1=max(xx0+1,int((tx+1)/SCALE))
            if a[yy0:yy1, xx0:xx1].min() < TH_INK:
                gy, gx = oy+ty, ox+tx
                if 0 <= gy < PET_H and 0 <= gx < PET_W:
                    g[gy][gx] = 1
    return g

GRIDS = [(name, trace(src)) for name, src in FRAMES]

def render(g, scale=6):
    im=Image.new("L",(PET_W*scale,PET_H*scale),255); d=ImageDraw.Draw(im)
    for y in range(PET_H):
        for x in range(PET_W):
            if g[y][x]: d.rectangle([x*scale,y*scale,x*scale+scale-1,y*scale+scale-1],fill=0)
    # ground line to check feet alignment
    fy=(PET_H-PAD_Y)*scale-1
    d.line([0,fy,PET_W*scale-1,fy],fill=160)
    return im

F=ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",14)
cols=4; rows=(len(GRIDS)+cols-1)//cols
cw=PET_W*6+8; chh=PET_H*6+20
m=Image.new("L",(cols*cw+8,rows*chh+8),255); dd=ImageDraw.Draw(m)
for i,(name,g) in enumerate(GRIDS):
    r,c=divmod(i,cols); x=8+c*cw; y=8+r*chh
    dd.text((x,y),name.replace("pet_",""),font=F,fill=0); m.paste(render(g),(x,y+16))
m.save("/tmp/sprite_frames.png"); print("preview /tmp/sprite_frames.png", m.size)

def to_bytes(g):
    stride=(PET_W+7)//8; out=[]
    for y in range(PET_H):
        for bx in range(stride):
            v=0
            for b in range(8):
                xx=bx*8+b
                if xx<PET_W and g[y][xx]: v|=0x80>>b
            out.append(v)
    return out
if "--emit" in sys.argv:
    def emit(f,name,g):
        b=to_bytes(g); f.write(f"static const uint8_t {name}[] = {{\n")
        for i in range(0,len(b),12): f.write("\t"+",".join(f"0x{v:02X}" for v in b[i:i+12])+",\n")
        f.write("};\n")
    with open(OUT,"w") as f:
        f.write("/* generated by sprite_gen.py from dog*.png - do not edit */\n#ifndef PETSPRITE_H\n#define PETSPRITE_H\n#include <stdint.h>\n")
        f.write(f"#define PET_W {PET_W}\n#define PET_H {PET_H}\n#define PET_STRIDE (({PET_W}+7)/8)\n")
        for name,g in GRIDS: emit(f,name,g)
        f.write("#endif\n")
    print("wrote",OUT)
